# ASAK Power Mode setup — Cursor / VS Code
# Usage:
#   .\scripts\powermode\setup-powermode.ps1                 # this workspace only
#   .\scripts\powermode\setup-powermode.ps1 -User            # user settings (all projects)
#   .\scripts\powermode\setup-powermode.ps1 -User -Editor Both
#
# Prerequisites: install extension "Power Mode" (hoovercj.vscode-power-mode)
# After run: Ctrl+Shift+P -> Developer: Reload Window

param(
    [switch]$User,
    [ValidateSet("Cursor", "Code", "Both")]
    [string]$Editor = "Both"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..\..")
$assetDir = Join-Path $scriptDir "assets"
$workspaceSettingsPath = Join-Path $repoRoot ".vscode\settings.json"

function Get-GifDataUris {
    param([string]$Directory)

    if (-not (Test-Path $Directory)) {
        throw "GIF folder not found: $Directory"
    }

    $gifs = Get-ChildItem -Path $Directory -Filter "*.gif" | Sort-Object Name
    if ($gifs.Count -eq 0) {
        throw "No GIF files in $Directory"
    }

    return @($gifs | ForEach-Object {
        $bytes = [IO.File]::ReadAllBytes($_.FullName)
        "data:image/gif;base64," + [Convert]::ToBase64String($bytes)
    })
}

function Get-PowerModeSettings {
    param([string[]]$CustomExplosions)

    return [ordered]@{
        "powermode.explosions.customExplosions" = $CustomExplosions
        "powermode.explosions.gifMode" = "continue"
        "powermode.explosions.explosionOrder" = "sequential"
        "powermode.explosions.duration" = 5000
        "powermode.explosions.frequency" = 1
        "powermode.explosions.maxExplosions" = 1
        "powermode.explosions.offset" = 1.2
        "powermode.explosions.size" = 8
        "powermode.explosions.customCss" = @{ "background-position" = "center bottom" }
        "powermode.explosions.backgroundMode" = "image"
        "powermode.combo.threshold" = 0
    }
}

function Get-UserPowerModeSettings {
    return [ordered]@{
        "powermode.enabled" = $true
        "powermode.shake.enabled" = $false
        "powermode.shake.intensity" = 0
        "powermode.combo.location" = "off"
        "powermode.combo.counterEnabled" = "hide"
        "powermode.combo.timerEnabled" = "hide"
        "powermode.combo.timeout" = 0
        "powermode.combo.counterSize" = 0
    }
}

function ConvertTo-SettingsJsonLine {
    param([string]$Key, $Value, [int]$Indent = 2)

    $pad = " " * $Indent

    if ($Value -is [array]) {
        $items = $Value | ForEach-Object { "`n$pad  `"$($_ -replace '"', '\"')`"" }
        return "$pad`"$Key`": [$($items -join ',')`n$pad]"
    }

    if ($Value -is [bool]) {
        return "$pad`"$Key`": $($Value.ToString().ToLower())"
    }

    if ($Value -is [hashtable]) {
        $inner = ($Value.GetEnumerator() | ForEach-Object {
            "$pad  `"$($_.Key)`": `"$($_.Value)`""
        }) -join ",`n"
        return "$pad`"$Key`": {`n$inner`n$pad}"
    }

    if ($Value -is [double] -or $Value -is [int]) {
        return "$pad`"$Key`": $Value"
    }

    return "$pad`"$Key`": `"$Value`""
}

function Write-WorkspaceSettings {
    param(
        [string]$Path,
        [hashtable]$PowerModeSettings
    )

    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }

    $lines = @(
        "{",
        "  // Power Mode — generated by scripts/powermode/setup-powermode.ps1",
        "  // GIF source: scripts/powermode/assets/*.gif",
        '  "java.configuration.updateBuildConfiguration": "interactive",',
        '  "java.compile.nullAnalysis.mode": "automatic",'
    )

    foreach ($entry in $PowerModeSettings.GetEnumerator()) {
        $lines += (ConvertTo-SettingsJsonLine -Key $entry.Key -Value $entry.Value) + ","
    }

    $lines[-1] = $lines[-1].TrimEnd(",")
    $lines += "}"

    Set-Content -Path $Path -Value ($lines -join "`n") -Encoding UTF8
}

function Update-UserSettingsFile {
    param(
        [string]$Path,
        [hashtable]$Settings
    )

    if (-not (Test-Path $Path)) {
        New-Item -ItemType File -Path $Path -Force | Out-Null
        $content = "{`n}"
    } else {
        $content = Get-Content $Path -Raw
    }

    foreach ($entry in $Settings.GetEnumerator()) {
        $key = [regex]::Escape($entry.Key)
        $line = (ConvertTo-SettingsJsonLine -Key $entry.Key -Value $entry.Value -Indent 2).TrimEnd(",")

        if ($entry.Key -eq "powermode.explosions.customExplosions") {
            if ($content -match "(?s)\s*`"$key`"\s*:\s*\[[^\]]*\],?") {
                $content = [regex]::Replace($content, "(?s)\s*`"$key`"\s*:\s*\[[^\]]*\],?", "`n  $line,")
            } else {
                $content = $content -replace "\{\s*", "{`n  $line,`n"
            }
            continue
        }

        if ($content -match "`"$key`"\s*:") {
            if ($entry.Value -is [bool]) {
                $replacement = "`"$($entry.Key)`": $($entry.Value.ToString().ToLower())"
            } elseif ($entry.Value -is [double] -or $entry.Value -is [int]) {
                $replacement = "`"$($entry.Key)`": $($entry.Value)"
            } else {
                $replacement = "`"$($entry.Key)`": `"$($entry.Value)`""
            }
            $content = [regex]::Replace($content, "`"$key`"\s*:\s*[^,\r\n}]+", $replacement)
        } else {
            $content = $content -replace "\{\s*", "{`n  $line,`n"
        }
    }

    $content = $content -replace ',\s*\r?\n}', "`n}"
    Set-Content -Path $Path -Value $content -NoNewline -Encoding UTF8
}

$dataUris = Get-GifDataUris -Directory $assetDir
$powerModeSettings = Get-PowerModeSettings -CustomExplosions $dataUris

Write-Host "GIF assets: $($dataUris.Count) file(s) from $assetDir"

if (-not $User) {
    Write-WorkspaceSettings -Path $workspaceSettingsPath -PowerModeSettings $powerModeSettings
    Write-Host "Updated workspace settings: $workspaceSettingsPath"
}

if ($User) {
    $userSettings = Get-UserPowerModeSettings
    foreach ($entry in $powerModeSettings.GetEnumerator()) {
        $userSettings[$entry.Key] = $entry.Value
    }

    $targets = @()
    if ($Editor -eq "Cursor" -or $Editor -eq "Both") {
        $targets += Join-Path $env:APPDATA "Cursor\User\settings.json"
    }
    if ($Editor -eq "Code" -or $Editor -eq "Both") {
        $targets += Join-Path $env:APPDATA "Code\User\settings.json"
    }

    foreach ($target in $targets) {
        Update-UserSettingsFile -Path $target -Settings $userSettings
        Write-Host "Updated user settings: $target"
    }
}

Write-Host ""
Write-Host "Done. Reload Window in Cursor/VS Code, then type in an editor."
Write-Host "Extension: hoovercj.vscode-power-mode"
